// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCwVAIAgEsqXjhFv5K3AS-gPPk0UCPRMA',
    appId: '1:975842573053:web:b52cd3e745e6f1c109dc94',
    messagingSenderId: '975842573053',
    projectId: 'employee-app-5f1e5',
    authDomain: 'employee-app-5f1e5.firebaseapp.com',
    storageBucket: 'employee-app-5f1e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeu90rYv4bkNy0ri7_hauZJPzqJOAqbz8',
    appId: '1:975842573053:android:28d4144e6f4d370009dc94',
    messagingSenderId: '975842573053',
    projectId: 'employee-app-5f1e5',
    storageBucket: 'employee-app-5f1e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5R_MWTZloshHL0_DEUzbU7JF6y56wigI',
    appId: '1:975842573053:ios:2efd6249d4be850309dc94',
    messagingSenderId: '975842573053',
    projectId: 'employee-app-5f1e5',
    storageBucket: 'employee-app-5f1e5.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5R_MWTZloshHL0_DEUzbU7JF6y56wigI',
    appId: '1:975842573053:ios:2efd6249d4be850309dc94',
    messagingSenderId: '975842573053',
    projectId: 'employee-app-5f1e5',
    storageBucket: 'employee-app-5f1e5.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCwVAIAgEsqXjhFv5K3AS-gPPk0UCPRMA',
    appId: '1:975842573053:web:7212c5c47d6fa87809dc94',
    messagingSenderId: '975842573053',
    projectId: 'employee-app-5f1e5',
    authDomain: 'employee-app-5f1e5.firebaseapp.com',
    storageBucket: 'employee-app-5f1e5.appspot.com',
  );
}